const products = [
    {
        id : 1,
        name : "Proteina",
        cantidad : 1,
        brand : "Optimum Nutrition",
        price : 900,
        img: "../imgs/store/wheyProtein.png",
        description : "Enhances muscle production, also helps on trainment recovery",
        video : "https://www.youtube.com/watch?v=Vie8HUL8ivE",
    },

    {
        id : 2,
        name : "BCAAS",
        cantidad : 1,
        brand : "Optimum Nutrition",
        img: '../imgs/store/BCAA.png',
        price : 500,
        description : "Promotes recovery through the ussage of Leucine, Isoleucine and Valine",
        video : "https://www.youtube.com/watch?v=SDRypbKUFaQ",
    },
    {
        id : 3,
        name : "Creatina",
        cantidad : 1,
        brand : "optimum Nutrition",
        img: '../imgs/store/creatinaOn.png',
        price :  450,
        description : "Increases endurance, boosts recovery and some cognitive process.",
        video : "https://www.youtube.com/watch?v=1vM_9FCtbvA",
    },
    {
        id : 4,
        name : "Cafeína",
        cantidad : 1,
        brand : "GAT",
        img: '../imgs/store/cafeinaGat.png',
        price : 300,
        description : "Increases your powersourse, promotes fat burn, slow down fatigue and helps with attention.",
        video : "https://www.youtube.com/watch?v=q7mWQnGQ7Vo",
    },
    {
        id : 5,
        name : "EAAS",
        cantidad : 1,
        brand : "GAT",
        img: '../imgs/store/EaasHydro.png',
        price : 550,
        description : "Promotes recovery with the Essential Amino Acids Leucine, Isoleucine, Valine, Histidine, Lysine, Methionine, Phenylalanine, Threonine, and Tryptophan.",
        video : "https://www.youtube.com/watch?v=XAKl218QlKM",
    },
    {
        id : 6,
        name : "Muscle Combo",
        cantidad : 1,
        brand : "Optimum Nutrition y GAT",
        img: '../imgs/store/cMusculo.png',
        price : 1500,
        description : "Includes protein, creatine and caffeine, ideal for accelerating musle creation helping with more intense exercise and improving endurance.",
        video : "https://www.youtube.com/watch?v=TK3wf-LjDG8",
    },
    {
        id : 7,
        name : "Combo Boost",
        cantidad : 1,
        brand : "Optimum Nutrition y GAT",
        img: '../imgs/store/cPotencia.png',
        price : 1100,
        description : "Includes creatine, BCAAS and caffeine, helps in the search of more endurande and accelerated recovery.",
        video : "https://www.youtube.com/watch?v=yCFmBdK0VHg",
    },
    {
        id : 8,
        name : "Combo Breaker",
        cantidad : 1,
        brand : "",
        img: '../imgs/store/cBreaker.png',
        price : 2000,
        description : "Includes protein, creatine, caffeine and EAAS, the perfect match for double trainings or with more frecuencies.",
        video : "https://www.youtube.com/watch?v=NwqUwzCyuR0",
    }
];